I've reorginized the files on the master branch
Phys767-Spring17/N-body pull request #3
Opened 2017-03-28 19:22 UTC by dcuffari

I like the way organized these files. I accept these changes.

2017-03-28 19:25 UTC, dcuffari reviewed
Good work! You don't suck after all.

2017-03-29 03:39 UTC, kelle requested changes
There are no tests implemented so this PR is not accepted.

2017-03-29 15:47 UTC, dcuffari commented
@ECGonzales I've made the changes that Kelle requested. Please review these changes.

2017-03-29 15:49 UTC, ECGonzales commented on .travis.yml
> +- py.test
do you like getting all the travis emails when you FAIL? If not add
notifications:
email:false

2017-03-29 15:50 UTC, ECGonzales commented on simulation/gravsim.py
> +    """
Where's the docstring??

2017-03-29 15:52 UTC, ECGonzales commented on simulation/gravsim.py
> +    """
DOCSTRING!

2017-03-29 15:53 UTC, dcuffari commented on .travis.yml
> +- py.test
Thanks, I've made this change.

2017-03-29 15:54 UTC, ECGonzales commented on tests/test_book.py
> +def test_book()
Is this finished? def needs colons after parenthesis.

2017-03-29 16:00 UTC, dcuffari commented on simulation/gravsim.py
> +    """
I've included the docstring.

2017-03-29 16:00 UTC, dcuffari commented on simulation/gravsim.py
> +    """
I've included the docstring.

2017-03-29 17:36 UTC, dcuffari commented on tests/test_book.py
> +def test_book()
I've completed the test.

2017-03-29 17:50 UTC, ECGonzales commented
This looks good to go now.

2017-04-05 15:11 UTC, kelle commented
- do you expect the tests to be passing?
- it looks like you are tracking too many files with github. There should be no .pyc files nor anything in the .cache directory tracked by git.

2017-04-05 16:56 UTC, kelle requested changes
it looks better than before I see files in __pycache__ which shouldnt be tracked.

2017-04-05 17:46 UTC, kelle requested changes
remove book.pyc

2017-04-05 17:51 UTC, dcuffari commented
I removed book.pyc please check again.

2017-04-05 17:53 UTC, kelle commented on requirements.txt
> +numpy.py
should just be numpy.

2017-05-03 14:29 UTC, dcuffari commented
I'm withdrawing my pull request. I need to make some branch changes and then I will re-issue a pull request. 

-Dave

2017-05-03 14:29 UTC, closed without merging